export const equipmentData = [
	{
	  id: 1,
	  joueur: "Leelou",
	  classe: "Paladin",
	  specialisation: "Protection",
	  role: "Tank",
	  tete: {
		name: "Set",
		color: "bg-blue-300",
		itemId: "12360",
		quality: "bis-nm"
	  },
	  cou: {
		name: "Torque Lumineux mystifié",
		color: "bg-yellow-300",
		itemId: "12345",
		quality: "bis-hm"
	  },
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "12346", quality: "bis-nm"},
	  cape: {name: "Linceul de porteur de bouclier", color: "bg-orange-400", itemId: "12347", quality: "non-bis-hm"},
	  torse: {name: "Plastron taillé dans l'écorchevif", color: "bg-purple-300", itemId: "12348", quality: "bis-mm"},
	  poignets: {name: "Brassards de Forge-destin", color: "bg-purple-500", itemId: "12349", quality: "non-bis-mm"},
	  mains: {name: "Gants d'affliction", color: "bg-purple-300", itemId: "12350", quality: "bis-mm"},
	  ceinture: {name: "Set", color: "bg-blue-300", itemId: "12351", quality: "bis-nm"},
	  jambes: {name: "Jambières accrocheuses", color: "bg-yellow-300", itemId: "12352", quality: "bis-hm"},
	  pieds: {name: "Sandales tressées", color: "bg-blue-300", itemId: "12353", quality: "bis-nm"},
	  anneau1: {name: "Anneau de gentil", color: "bg-purple-500", itemId: "12354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague chaude", color: "bg-orange-400", itemId: "12355", quality: "non-bis-hm"},
	  bijou1: {name: "Insigne de Brise-roche", color: "bg-blue-300", itemId: "12356", quality: "bis-nm"},
	  bijou2: {name: "Coupe de Brise-roche", color: "bg-yellow-300", itemId: "12357", quality: "bis-hm"},
	  arme1: {name: "Marteau de Brise-roche", color: "bg-purple-300", itemId: "12358", quality: "bis-mm"},
	  arme2: {name: "Bouclier végétalisé", color: "bg-purple-500", itemId: "12359", quality: "non-bis-mm"},
	  ilvl: 666,
	  hasPermission: true
	},
	{
	  id: 2,
	  joueur: "Carla",
	  classe: "Chasseur",
	  specialisation: "Précision",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "22360", quality: "bis-nm"},
	  cou: {name: "Collier d'acuité", color: "bg-purple-500", itemId: "22345", quality: "non-bis-mm"},
	  epaules: {name: "Épaulières de visée", color: "bg-yellow-300", itemId: "22346", quality: "bis-hm"},
	  cape: {name: "Cape du traqueur", color: "bg-orange-400", itemId: "22347", quality: "non-bis-hm"},
	  torse: {name: "Plastron du chasseur", color: "bg-purple-300", itemId: "22348", quality: "bis-mm"},
	  poignets: {name: "Bracelets de précision", color: "bg-blue-300", itemId: "22349", quality: "bis-nm"},
	  mains: {name: "Gants du tireur d'élite", color: "bg-yellow-300", itemId: "22350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de munitions", color: "bg-purple-500", itemId: "22351", quality: "non-bis-mm"},
	  jambes: {name: "Jambières de vétéran", color: "bg-blue-300", itemId: "22352", quality: "bis-nm"},
	  pieds: {name: "Bottes du voyageur", color: "bg-orange-400", itemId: "22353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de précision", color: "bg-purple-300", itemId: "22354", quality: "bis-mm"},
	  anneau2: {name: "Chevalière du faucon", color: "bg-blue-300", itemId: "22355", quality: "bis-nm"},
	  bijou1: {name: "Insigne du chasseur", color: "bg-yellow-300", itemId: "22356", quality: "bis-hm"},
	  bijou2: {name: "Médaillon de visée", color: "bg-purple-500", itemId: "22357", quality: "non-bis-mm"},
	  arme1: {name: "Arc de longue portée", color: "bg-blue-300", itemId: "22358", quality: "bis-nm"},
	  arme2: {name: "Couteau de survie", color: "bg-orange-400", itemId: "22359", quality: "non-bis-hm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 3,
	  joueur: "Pamplemousse",
	  classe: "Mage",
	  specialisation: "Givre",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "32360", quality: "bis-nm"},
	  cou: {name: "Amulette glaciale", color: "bg-yellow-300", itemId: "32345", quality: "bis-hm"},
	  epaules: {name: "Épaulières du blizzard", color: "bg-purple-300", itemId: "32346", quality: "bis-mm"},
	  cape: {name: "Cape du gel", color: "bg-purple-500", itemId: "32347", quality: "non-bis-mm"},
	  torse: {name: "Robe de l'hiver", color: "bg-blue-300", itemId: "32348", quality: "bis-nm"},
	  poignets: {name: "Brassards gelés", color: "bg-orange-400", itemId: "32349", quality: "non-bis-hm"},
	  mains: {name: "Gants de givre", color: "bg-yellow-300", itemId: "32350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture du blizzard", color: "bg-blue-300", itemId: "32351", quality: "bis-nm"},
	  jambes: {name: "Jambières de glace", color: "bg-purple-300", itemId: "32352", quality: "bis-mm"},
	  pieds: {name: "Bottines de neige", color: "bg-purple-500", itemId: "32353", quality: "non-bis-mm"},
	  anneau1: {name: "Anneau givré", color: "bg-blue-300", itemId: "32354", quality: "bis-nm"},
	  anneau2: {name: "Bague de l'arctique", color: "bg-orange-400", itemId: "32355", quality: "non-bis-hm"},
	  bijou1: {name: "Médaillon du mage", color: "bg-yellow-300", itemId: "32356", quality: "bis-hm"},
	  bijou2: {name: "Charme du froid", color: "bg-purple-300", itemId: "32357", quality: "bis-mm"},
	  arme1: {name: "Bâton de givre", color: "bg-purple-500", itemId: "32358", quality: "non-bis-mm"},
	  arme2: {name: "Orbe de gel", color: "bg-blue-300", itemId: "32359", quality: "bis-nm"},
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 4,
	  joueur: "Deathfire",
	  classe: "Démoniste",
	  specialisation: "Affliction",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "42360", quality: "bis-nm"},
	  cou: {name: "Collier d'âmes", color: "bg-purple-300", itemId: "42345", quality: "bis-mm"},
	  epaules: {name: "Épaulières de tourment", color: "bg-purple-500", itemId: "42346", quality: "non-bis-mm"},
	  cape: {name: "Cape des ombres", color: "bg-blue-300", itemId: "42347", quality: "bis-nm"},
	  torse: {name: "Robe de l'affliction", color: "bg-orange-400", itemId: "42348", quality: "non-bis-hm"},
	  poignets: {name: "Brassards des ténèbres", color: "bg-yellow-300", itemId: "42349", quality: "bis-hm"},
	  mains: {name: "Gants du tourmenteur", color: "bg-blue-300", itemId: "42350", quality: "bis-nm"},
	  ceinture: {name: "Ceinture du vide", color: "bg-purple-300", itemId: "42351", quality: "bis-mm"},
	  jambes: {name: "Jambières d'agonie", color: "bg-purple-500", itemId: "42352", quality: "non-bis-mm"},
	  pieds: {name: "Bottines de fléau", color: "bg-blue-300", itemId: "42353", quality: "bis-nm"},
	  anneau1: {name: "Anneau d'affliction", color: "bg-orange-400", itemId: "42354", quality: "non-bis-hm"},
	  anneau2: {name: "Bague de corruption", color: "bg-yellow-300", itemId: "42355", quality: "bis-hm"},
	  bijou1: {name: "Charme de malédiction", color: "bg-blue-300", itemId: "42356", quality: "bis-nm"},
	  bijou2: {name: "Médaillon du démoniste", color: "bg-purple-300", itemId: "42357", quality: "bis-mm"},
	  arme1: {name: "Bâton d'agonie", color: "bg-purple-500", itemId: "42358", quality: "non-bis-mm"},
	  arme2: {name: "Grimoire des ombres", color: "bg-blue-300", itemId: "42359", quality: "bis-nm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 5,
	  joueur: "Yikaru",
	  classe: "Druide",
	  specialisation: "Restauration",
	  role: "Healer",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "52360", quality: "bis-nm"},
	  cou: {name: "Amulette de verdure", color: "bg-yellow-300", itemId: "52345", quality: "bis-hm"},
	  epaules: {name: "Épaulières de floraison", color: "bg-blue-300", itemId: "52346", quality: "bis-nm"},
	  cape: {name: "Cape de régénération", color: "bg-purple-300", itemId: "52347", quality: "bis-mm"},
	  torse: {name: "Robe de guérison", color: "bg-purple-500", itemId: "52348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards de croissance", color: "bg-blue-300", itemId: "52349", quality: "bis-nm"},
	  mains: {name: "Gants de soigneur", color: "bg-orange-400", itemId: "52350", quality: "non-bis-hm"},
	  ceinture: {name: "Ceinture de vie", color: "bg-yellow-300", itemId: "52351", quality: "bis-hm"},
	  jambes: {name: "Jambières de restauration", color: "bg-blue-300", itemId: "52352", quality: "bis-nm"},
	  pieds: {name: "Bottines de la forêt", color: "bg-purple-300", itemId: "52353", quality: "bis-mm"},
	  anneau1: {name: "Anneau de rejuvenation", color: "bg-purple-500", itemId: "52354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague d'épanouissement", color: "bg-blue-300", itemId: "52355", quality: "bis-nm"},
	  bijou1: {name: "Idole de guérison", color: "bg-orange-400", itemId: "52356", quality: "non-bis-hm"},
	  bijou2: {name: "Charme de renaissance", color: "bg-yellow-300", itemId: "52357", quality: "bis-hm"},
	  arme1: {name: "Bâton de floraison", color: "bg-blue-300", itemId: "52358", quality: "bis-nm"},
	  arme2: {name: "Bouclier de régénération", color: "bg-purple-300", itemId: "52359", quality: "bis-mm"},
	  ilvl: 667,
	  hasPermission: true
	},
	// Added players start here
	{
	  id: 6,
	  joueur: "Zorg",
	  classe: "Guerrier",
	  specialisation: "Fureur",
	  role: "DPS",
	  tete: {name: "Heaume de bataille", color: "bg-yellow-300", itemId: "62360", quality: "bis-hm"},
	  cou: {name: "Collier de rage", color: "bg-purple-300", itemId: "62345", quality: "bis-mm"},
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "62346", quality: "bis-nm"},
	  cape: {name: "Cape de berserker", color: "bg-orange-400", itemId: "62347", quality: "non-bis-hm"},
	  torse: {name: "Cuirasse du combattant", color: "bg-purple-500", itemId: "62348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards de force", color: "bg-blue-300", itemId: "62349", quality: "bis-nm"},
	  mains: {name: "Gantelets de frappe", color: "bg-yellow-300", itemId: "62350", quality: "bis-hm"},
	  ceinture: {name: "Ceinturon de puissance", color: "bg-purple-300", itemId: "62351", quality: "bis-mm"},
	  jambes: {name: "Jambières de charge", color: "bg-blue-300", itemId: "62352", quality: "bis-nm"},
	  pieds: {name: "Bottes de guerre", color: "bg-orange-400", itemId: "62353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de fureur", color: "bg-purple-500", itemId: "62354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague du guerrier", color: "bg-yellow-300", itemId: "62355", quality: "bis-hm"},
	  bijou1: {name: "Insigne de force", color: "bg-blue-300", itemId: "62356", quality: "bis-nm"},
	  bijou2: {name: "Talisman de rage", color: "bg-purple-300", itemId: "62357", quality: "bis-mm"},
	  arme1: {name: "Hache de fureur", color: "bg-blue-300", itemId: "62358", quality: "bis-nm"},
	  arme2: {name: "Hache de rage", color: "bg-orange-400", itemId: "62359", quality: "non-bis-hm"},
	  ilvl: 669,
	  hasPermission: true
	},
	{
	  id: 7,
	  joueur: "Anya",
	  classe: "Prêtre",
	  specialisation: "Discipline",
	  role: "Healer",
	  tete: {name: "Couronne de foi", color: "bg-purple-300", itemId: "72360", quality: "bis-mm"},
	  cou: {name: "Pendentif sacré", color: "bg-blue-300", itemId: "72345", quality: "bis-nm"},
	  epaules: {name: "Épaulières de lumière", color: "bg-yellow-300", itemId: "72346", quality: "bis-hm"},
	  cape: {name: "Cape de pénitence", color: "bg-purple-500", itemId: "72347", quality: "non-bis-mm"},
	  torse: {name: "Robe de discipline", color: "bg-orange-400", itemId: "72348", quality: "non-bis-hm"},
	  poignets: {name: "Brassards de prière", color: "bg-blue-300", itemId: "72349", quality: "bis-nm"},
	  mains: {name: "Gants de foi", color: "bg-purple-300", itemId: "72350", quality: "bis-mm"},
	  ceinture: {name: "Ceinture de vertu", color: "bg-yellow-300", itemId: "72351", quality: "bis-hm"},
	  jambes: {name: "Jambières de lumière", color: "bg-purple-500", itemId: "72352", quality: "non-bis-mm"},
	  pieds: {name: "Sandales sacrées", color: "bg-blue-300", itemId: "72353", quality: "bis-nm"},
	  anneau1: {name: "Anneau de discipline", color: "bg-orange-400", itemId: "72354", quality: "non-bis-hm"},
	  anneau2: {name: "Bague de prière", color: "bg-yellow-300", itemId: "72355", quality: "bis-hm"},
	  bijou1: {name: "Symbole de foi", color: "bg-purple-300", itemId: "72356", quality: "bis-mm"},
	  bijou2: {name: "Charme de pénitence", color: "bg-blue-300", itemId: "72357", quality: "bis-nm"},
	  arme1: {name: "Masse sacrée", color: "bg-purple-500", itemId: "72358", quality: "non-bis-mm"},
	  arme2: {name: "Livre de prières", color: "bg-orange-400", itemId: "72359", quality: "non-bis-hm"},
	  ilvl: 665,
	  hasPermission: true
	},
	{
	  id: 8,
	  joueur: "Kael",
	  classe: "Voleur",
	  specialisation: "Assassinat",
	  role: "DPS",
	  tete: {name: "Masque de l'ombre", color: "bg-blue-300", itemId: "82360", quality: "bis-nm"},
	  cou: {name: "Collier de poison", color: "bg-orange-400", itemId: "82345", quality: "non-bis-hm"},
	  epaules: {name: "Épaulières furtives", color: "bg-purple-300", itemId: "82346", quality: "bis-mm"},
	  cape: {name: "Cape d'assassin", color: "bg-yellow-300", itemId: "82347", quality: "bis-hm"},
	  torse: {name: "Cuirasse de l'ombre", color: "bg-blue-300", itemId: "82348", quality: "bis-nm"},
	  poignets: {name: "Brassards de célérité", color: "bg-purple-500", itemId: "82349", quality: "non-bis-mm"},
	  mains: {name: "Gants de précision", color: "bg-orange-400", itemId: "82350", quality: "non-bis-hm"},
	  ceinture: {name: "Ceinture de lames", color: "bg-blue-300", itemId: "82351", quality: "bis-nm"},
	  jambes: {name: "Jambières d'assassin", color: "bg-yellow-300", itemId: "82352", quality: "bis-hm"},
	  pieds: {name: "Bottes silencieuses", color: "bg-purple-300", itemId: "82353", quality: "bis-mm"},
	  anneau1: {name: "Anneau de venin", color: "bg-blue-300", itemId: "82354", quality: "bis-nm"},
	  anneau2: {name: "Bague de l'ombre", color: "bg-purple-500", itemId: "82355", quality: "non-bis-mm"},
	  bijou1: {name: "Insigne de voleur", color: "bg-yellow-300", itemId: "82356", quality: "bis-hm"},
	  bijou2: {name: "Talisman d'agilité", color: "bg-orange-400", itemId: "82357", quality: "non-bis-hm"},
	  arme1: {name: "Dague empoisonnée", color: "bg-purple-300", itemId: "82358", quality: "bis-mm"},
	  arme2: {name: "Dague rapide", color: "bg-blue-300", itemId: "82359", quality: "bis-nm"},
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 9,
	  joueur: "Elara",
	  classe: "Chaman",
	  specialisation: "Élémentaire",
	  role: "DPS",
	  tete: {name: "Casque totémique", color: "bg-yellow-300", itemId: "92360", quality: "bis-hm"},
	  cou: {name: "Amulette des éléments", color: "bg-blue-300", itemId: "92345", quality: "bis-nm"},
	  epaules: {name: "Set", color: "bg-purple-300", itemId: "92346", quality: "bis-mm"},
	  cape: {name: "Cape de tempête", color: "bg-orange-400", itemId: "92347", quality: "non-bis-hm"},
	  torse: {name: "Harnois de foudre", color: "bg-purple-500", itemId: "92348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards sismiques", color: "bg-yellow-300", itemId: "92349", quality: "bis-hm"},
	  mains: {name: "Gants de lave", color: "bg-blue-300", itemId: "92350", quality: "bis-nm"},
	  ceinture: {name: "Ceinture tellurique", color: "bg-purple-300", itemId: "92351", quality: "bis-mm"},
	  jambes: {name: "Kilt des éléments", color: "bg-orange-400", itemId: "92352", quality: "non-bis-hm"},
	  pieds: {name: "Bottes de marche-esprit", color: "bg-yellow-300", itemId: "92353", quality: "bis-hm"},
	  anneau1: {name: "Anneau de foudre", color: "bg-blue-300", itemId: "92354", quality: "bis-nm"},
	  anneau2: {name: "Bague de magma", color: "bg-purple-500", itemId: "92355", quality: "non-bis-mm"},
	  bijou1: {name: "Totem élémentaire", color: "bg-purple-300", itemId: "92356", quality: "bis-mm"},
	  bijou2: {name: "Charme de tempête", color: "bg-orange-400", itemId: "92357", quality: "non-bis-hm"},
	  arme1: {name: "Masse de foudre", color: "bg-yellow-300", itemId: "92358", quality: "bis-hm"},
	  arme2: {name: "Bouclier des éléments", color: "bg-blue-300", itemId: "92359", quality: "bis-nm"},
	  ilvl: 666,
	  hasPermission: true
	},
	{
	  id: 10,
	  joueur: "Roric",
	  classe: "Chevalier de la mort",
	  specialisation: "Givre",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "102360", quality: "bis-nm"},
	  cou: {name: "Collier runique", color: "bg-purple-500", itemId: "102345", quality: "non-bis-mm"},
	  epaules: {name: "Épaulières de la mort", color: "bg-yellow-300", itemId: "102346", quality: "bis-hm"},
	  cape: {name: "Cape glaciale", color: "bg-orange-400", itemId: "102347", quality: "non-bis-hm"},
	  torse: {name: "Cuirasse du fléau", color: "bg-purple-300", itemId: "102348", quality: "bis-mm"},
	  poignets: {name: "Brassards de givre", color: "bg-blue-300", itemId: "102349", quality: "bis-nm"},
	  mains: {name: "Gantelets runiques", color: "bg-yellow-300", itemId: "102350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de la mort", color: "bg-purple-500", itemId: "102351", quality: "non-bis-mm"},
	  jambes: {name: "Jambières du fléau", color: "bg-blue-300", itemId: "102352", quality: "bis-nm"},
	  pieds: {name: "Bottes de givre", color: "bg-orange-400", itemId: "102353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau runique", color: "bg-purple-300", itemId: "102354", quality: "bis-mm"},
	  anneau2: {name: "Bague glaciale", color: "bg-blue-300", itemId: "102355", quality: "bis-nm"},
	  bijou1: {name: "Sceau de la mort", color: "bg-yellow-300", itemId: "102356", quality: "bis-hm"},
	  bijou2: {name: "Talisman de givre", color: "bg-purple-500", itemId: "102357", quality: "non-bis-mm"},
	  arme1: {name: "Lame runique de givre", color: "bg-blue-300", itemId: "102358", quality: "bis-nm"},
	  arme2: {name: "Lame runique de glace", color: "bg-orange-400", itemId: "102359", quality: "non-bis-hm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 11,
	  joueur: "Silvana",
	  classe: "Moine",
	  specialisation: "Tisse-brume",
	  role: "Healer",
	  tete: {name: "Chapeau de brume", color: "bg-purple-300", itemId: "112360", quality: "bis-mm"},
	  cou: {name: "Amulette de sérénité", color: "bg-yellow-300", itemId: "112345", quality: "bis-hm"},
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "112346", quality: "bis-nm"},
	  cape: {name: "Cape de quiétude", color: "bg-orange-400", itemId: "112347", quality: "non-bis-hm"},
	  torse: {name: "Robe de tisseur", color: "bg-purple-500", itemId: "112348", quality: "non-bis-mm"},
	  poignets: {name: "Bandes de méditation", color: "bg-blue-300", itemId: "112349", quality: "bis-nm"},
	  mains: {name: "Gants de brume", color: "bg-yellow-300", itemId: "112350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de sérénité", color: "bg-purple-300", itemId: "112351", quality: "bis-mm"},
	  jambes: {name: "Pantalon de tisseur", color: "bg-blue-300", itemId: "112352", quality: "bis-nm"},
	  pieds: {name: "Chaussons de quiétude", color: "bg-orange-400", itemId: "112353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de brume", color: "bg-purple-500", itemId: "112354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague de méditation", color: "bg-yellow-300", itemId: "112355", quality: "bis-hm"},
	  bijou1: {name: "Perle de sérénité", color: "bg-blue-300", itemId: "112356", quality: "bis-nm"},
	  bijou2: {name: "Charme de tisseur", color: "bg-purple-300", itemId: "112357", quality: "bis-mm"},
	  arme1: {name: "Bâton de brume", color: "bg-blue-300", itemId: "112358", quality: "bis-nm"},
	  arme2: {name: "Orbe de quiétude", color: "bg-orange-400", itemId: "112359", quality: "non-bis-hm"},
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 12,
	  joueur: "Borin",
	  classe: "Paladin",
	  specialisation: "Vindicte",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-yellow-300", itemId: "122360", quality: "bis-hm"},
	  cou: {name: "Collier de jugement", color: "bg-purple-300", itemId: "122345", quality: "bis-mm"},
	  epaules: {name: "Épaulières de lumière", color: "bg-blue-300", itemId: "122346", quality: "bis-nm"},
	  cape: {name: "Cape de croisade", color: "bg-orange-400", itemId: "122347", quality: "non-bis-hm"},
	  torse: {name: "Cuirasse de vindicte", color: "bg-purple-500", itemId: "122348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards sacrés", color: "bg-blue-300", itemId: "122349", quality: "bis-nm"},
	  mains: {name: "Gantelets de jugement", color: "bg-yellow-300", itemId: "122350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de croisade", color: "bg-purple-300", itemId: "122351", quality: "bis-mm"},
	  jambes: {name: "Jambières de lumière", color: "bg-blue-300", itemId: "122352", quality: "bis-nm"},
	  pieds: {name: "Bottes de vindicte", color: "bg-orange-400", itemId: "122353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de jugement", color: "bg-purple-500", itemId: "122354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague sacrée", color: "bg-yellow-300", itemId: "122355", quality: "bis-hm"},
	  bijou1: {name: "Sceau de lumière", color: "bg-blue-300", itemId: "122356", quality: "bis-nm"},
	  bijou2: {name: "Talisman de croisade", color: "bg-purple-300", itemId: "122357", quality: "bis-mm"},
	  arme1: {name: "Espadon de vindicte", color: "bg-yellow-300", itemId: "122358", quality: "bis-hm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 669,
	  hasPermission: true
	},
	{
	  id: 13,
	  joueur: "Fiona",
	  classe: "Chasseur",
	  specialisation: "Maîtrise des bêtes",
	  role: "DPS",
	  tete: {name: "Heaume de traqueur", color: "bg-purple-300", itemId: "132360", quality: "bis-mm"},
	  cou: {name: "Collier bestial", color: "bg-blue-300", itemId: "132345", quality: "bis-nm"},
	  epaules: {name: "Set", color: "bg-yellow-300", itemId: "132346", quality: "bis-hm"},
	  cape: {name: "Cape sauvage", color: "bg-purple-500", itemId: "132347", quality: "non-bis-mm"},
	  torse: {name: "Harnois de maître", color: "bg-orange-400", itemId: "132348", quality: "non-bis-hm"},
	  poignets: {name: "Brassards de pistage", color: "bg-blue-300", itemId: "132349", quality: "bis-nm"},
	  mains: {name: "Gants de dompteur", color: "bg-purple-300", itemId: "132350", quality: "bis-mm"},
	  ceinture: {name: "Ceinture de chasse", color: "bg-yellow-300", itemId: "132351", quality: "bis-hm"},
	  jambes: {name: "Jambières de traqueur", color: "bg-purple-500", itemId: "132352", quality: "non-bis-mm"},
	  pieds: {name: "Bottes de pisteur", color: "bg-blue-300", itemId: "132353", quality: "bis-nm"},
	  anneau1: {name: "Anneau bestial", color: "bg-orange-400", itemId: "132354", quality: "non-bis-hm"},
	  anneau2: {name: "Bague de maître", color: "bg-yellow-300", itemId: "132355", quality: "bis-hm"},
	  bijou1: {name: "Insigne de chasseur", color: "bg-purple-300", itemId: "132356", quality: "bis-mm"},
	  bijou2: {name: "Charme sauvage", color: "bg-blue-300", itemId: "132357", quality: "bis-nm"},
	  arme1: {name: "Fusil de maître", color: "bg-purple-500", itemId: "132358", quality: "non-bis-mm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // Ranged weapon
	  ilvl: 665,
	  hasPermission: true
	},
	{
	  id: 14,
	  joueur: "Grak",
	  classe: "Guerrier",
	  specialisation: "Protection",
	  role: "Tank",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "142360", quality: "bis-nm"},
	  cou: {name: "Torque de bastion", color: "bg-orange-400", itemId: "142345", quality: "non-bis-hm"},
	  epaules: {name: "Épaulières de défense", color: "bg-purple-300", itemId: "142346", quality: "bis-mm"},
	  cape: {name: "Cape de rempart", color: "bg-yellow-300", itemId: "142347", quality: "bis-hm"},
	  torse: {name: "Cuirasse de gardien", color: "bg-blue-300", itemId: "142348", quality: "bis-nm"},
	  poignets: {name: "Brassards de protection", color: "bg-purple-500", itemId: "142349", quality: "non-bis-mm"},
	  mains: {name: "Gantelets de bastion", color: "bg-orange-400", itemId: "142350", quality: "non-bis-hm"},
	  ceinture: {name: "Ceinture de défense", color: "bg-blue-300", itemId: "142351", quality: "bis-nm"},
	  jambes: {name: "Jambières de gardien", color: "bg-yellow-300", itemId: "142352", quality: "bis-hm"},
	  pieds: {name: "Bottes de rempart", color: "bg-purple-300", itemId: "142353", quality: "bis-mm"},
	  anneau1: {name: "Anneau de protection", color: "bg-blue-300", itemId: "142354", quality: "bis-nm"},
	  anneau2: {name: "Bague de bastion", color: "bg-purple-500", itemId: "142355", quality: "non-bis-mm"},
	  bijou1: {name: "Insigne de défense", color: "bg-yellow-300", itemId: "142356", quality: "bis-hm"},
	  bijou2: {name: "Talisman de gardien", color: "bg-orange-400", itemId: "142357", quality: "non-bis-hm"},
	  arme1: {name: "Épée de protection", color: "bg-purple-300", itemId: "142358", quality: "bis-mm"},
	  arme2: {name: "Bouclier de rempart", color: "bg-blue-300", itemId: "142359", quality: "bis-nm"},
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 15,
	  joueur: "Lyra",
	  classe: "Mage",
	  specialisation: "Arcane",
	  role: "DPS",
	  tete: {name: "Diadème arcanique", color: "bg-yellow-300", itemId: "152360", quality: "bis-hm"},
	  cou: {name: "Pendentif de puissance", color: "bg-blue-300", itemId: "152345", quality: "bis-nm"},
	  epaules: {name: "Set", color: "bg-purple-300", itemId: "152346", quality: "bis-mm"},
	  cape: {name: "Cape de sort", color: "bg-orange-400", itemId: "152347", quality: "non-bis-hm"},
	  torse: {name: "Robe des arcanes", color: "bg-purple-500", itemId: "152348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards de mana", color: "bg-yellow-300", itemId: "152349", quality: "bis-hm"},
	  mains: {name: "Gants de puissance", color: "bg-blue-300", itemId: "152350", quality: "bis-nm"},
	  ceinture: {name: "Ceinture arcanique", color: "bg-purple-300", itemId: "152351", quality: "bis-mm"},
	  jambes: {name: "Jambières de sort", color: "bg-orange-400", itemId: "152352", quality: "non-bis-hm"},
	  pieds: {name: "Chaussures de mana", color: "bg-yellow-300", itemId: "152353", quality: "bis-hm"},
	  anneau1: {name: "Anneau arcanique", color: "bg-blue-300", itemId: "152354", quality: "bis-nm"},
	  anneau2: {name: "Bague de puissance", color: "bg-purple-500", itemId: "152355", quality: "non-bis-mm"},
	  bijou1: {name: "Cristal de mana", color: "bg-purple-300", itemId: "152356", quality: "bis-mm"},
	  bijou2: {name: "Charme de sort", color: "bg-orange-400", itemId: "152357", quality: "non-bis-hm"},
	  arme1: {name: "Bâton des arcanes", color: "bg-yellow-300", itemId: "152358", quality: "bis-hm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 666,
	  hasPermission: true
	},
	{
	  id: 16,
	  joueur: "Zaltar",
	  classe: "Démoniste",
	  specialisation: "Démonologie",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "162360", quality: "bis-nm"},
	  cou: {name: "Collier démoniaque", color: "bg-purple-500", itemId: "162345", quality: "non-bis-mm"},
	  epaules: {name: "Épaulières d'invocation", color: "bg-yellow-300", itemId: "162346", quality: "bis-hm"},
	  cape: {name: "Cape de gangrène", color: "bg-orange-400", itemId: "162347", quality: "non-bis-hm"},
	  torse: {name: "Robe de démonologue", color: "bg-purple-300", itemId: "162348", quality: "bis-mm"},
	  poignets: {name: "Brassards d'invocation", color: "bg-blue-300", itemId: "162349", quality: "bis-nm"},
	  mains: {name: "Gants gangrenés", color: "bg-yellow-300", itemId: "162350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture démoniaque", color: "bg-purple-500", itemId: "162351", quality: "non-bis-mm"},
	  jambes: {name: "Jambières d'invocation", color: "bg-blue-300", itemId: "162352", quality: "bis-nm"},
	  pieds: {name: "Bottes de gangrène", color: "bg-orange-400", itemId: "162353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau démoniaque", color: "bg-purple-300", itemId: "162354", quality: "bis-mm"},
	  anneau2: {name: "Bague d'invocation", color: "bg-blue-300", itemId: "162355", quality: "bis-nm"},
	  bijou1: {name: "Fragment d'âme", color: "bg-yellow-300", itemId: "162356", quality: "bis-hm"},
	  bijou2: {name: "Talisman gangrené", color: "bg-purple-500", itemId: "162357", quality: "non-bis-mm"},
	  arme1: {name: "Bâton d'invocation", color: "bg-blue-300", itemId: "162358", quality: "bis-nm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 17,
	  joueur: "Mira",
	  classe: "Druide",
	  specialisation: "Équilibre",
	  role: "DPS",
	  tete: {name: "Coiffe lunaire", color: "bg-purple-300", itemId: "172360", quality: "bis-mm"},
	  cou: {name: "Amulette stellaire", color: "bg-yellow-300", itemId: "172345", quality: "bis-hm"},
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "172346", quality: "bis-nm"},
	  cape: {name: "Cape céleste", color: "bg-orange-400", itemId: "172347", quality: "non-bis-hm"},
	  torse: {name: "Robe d'équilibre", color: "bg-purple-500", itemId: "172348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards lunaires", color: "bg-blue-300", itemId: "172349", quality: "bis-nm"},
	  mains: {name: "Gants stellaires", color: "bg-yellow-300", itemId: "172350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture céleste", color: "bg-purple-300", itemId: "172351", quality: "bis-mm"},
	  jambes: {name: "Jambières d'équilibre", color: "bg-blue-300", itemId: "172352", quality: "bis-nm"},
	  pieds: {name: "Sandales lunaires", color: "bg-orange-400", itemId: "172353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau stellaire", color: "bg-purple-500", itemId: "172354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague céleste", color: "bg-yellow-300", itemId: "172355", quality: "bis-hm"},
	  bijou1: {name: "Idole lunaire", color: "bg-blue-300", itemId: "172356", quality: "bis-nm"},
	  bijou2: {name: "Charme d'équilibre", color: "bg-purple-300", itemId: "172357", quality: "bis-mm"},
	  arme1: {name: "Bâton stellaire", color: "bg-blue-300", itemId: "172358", quality: "bis-nm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 18,
	  joueur: "Torvin",
	  classe: "Prêtre",
	  specialisation: "Ombre",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "182360", quality: "bis-nm"},
	  cou: {name: "Pendentif du vide", color: "bg-orange-400", itemId: "182345", quality: "non-bis-hm"},
	  epaules: {name: "Épaulières d'ombre", color: "bg-purple-300", itemId: "182346", quality: "bis-mm"},
	  cape: {name: "Cape de démence", color: "bg-yellow-300", itemId: "182347", quality: "bis-hm"},
	  torse: {name: "Robe du vide", color: "bg-blue-300", itemId: "182348", quality: "bis-nm"},
	  poignets: {name: "Brassards d'ombre", color: "bg-purple-500", itemId: "182349", quality: "non-bis-mm"},
	  mains: {name: "Gants de démence", color: "bg-orange-400", itemId: "182350", quality: "non-bis-hm"},
	  ceinture: {name: "Ceinture du vide", color: "bg-blue-300", itemId: "182351", quality: "bis-nm"},
	  jambes: {name: "Jambières d'ombre", color: "bg-yellow-300", itemId: "182352", quality: "bis-hm"},
	  pieds: {name: "Chaussures de démence", color: "bg-purple-300", itemId: "182353", quality: "bis-mm"},
	  anneau1: {name: "Anneau du vide", color: "bg-blue-300", itemId: "182354", quality: "bis-nm"},
	  anneau2: {name: "Bague d'ombre", color: "bg-purple-500", itemId: "182355", quality: "non-bis-mm"},
	  bijou1: {name: "Idole d'ombre", color: "bg-yellow-300", itemId: "182356", quality: "bis-hm"},
	  bijou2: {name: "Charme de démence", color: "bg-orange-400", itemId: "182357", quality: "non-bis-hm"},
	  arme1: {name: "Dague d'ombre", color: "bg-purple-300", itemId: "182358", quality: "bis-mm"},
	  arme2: {name: "Orbe du vide", color: "bg-blue-300", itemId: "182359", quality: "bis-nm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 19,
	  joueur: "Shandra",
	  classe: "Voleur",
	  specialisation: "Finesse",
	  role: "DPS",
	  tete: {name: "Capuche de finesse", color: "bg-yellow-300", itemId: "192360", quality: "bis-hm"},
	  cou: {name: "Collier d'esquive", color: "bg-blue-300", itemId: "192345", quality: "bis-nm"},
	  epaules: {name: "Set", color: "bg-purple-300", itemId: "192346", quality: "bis-mm"},
	  cape: {name: "Cape d'ombre", color: "bg-orange-400", itemId: "192347", quality: "non-bis-hm"},
	  torse: {name: "Cuirasse de finesse", color: "bg-purple-500", itemId: "192348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards d'agilité", color: "bg-yellow-300", itemId: "192349", quality: "bis-hm"},
	  mains: {name: "Gants d'esquive", color: "bg-blue-300", itemId: "192350", quality: "bis-nm"},
	  ceinture: {name: "Ceinture d'ombre", color: "bg-purple-300", itemId: "192351", quality: "bis-mm"},
	  jambes: {name: "Jambières de finesse", color: "bg-orange-400", itemId: "192352", quality: "non-bis-hm"},
	  pieds: {name: "Bottes d'agilité", color: "bg-yellow-300", itemId: "192353", quality: "bis-hm"},
	  anneau1: {name: "Anneau d'esquive", color: "bg-blue-300", itemId: "192354", quality: "bis-nm"},
	  anneau2: {name: "Bague d'ombre", color: "bg-purple-500", itemId: "192355", quality: "non-bis-mm"},
	  bijou1: {name: "Insigne de finesse", color: "bg-purple-300", itemId: "192356", quality: "bis-mm"},
	  bijou2: {name: "Talisman d'agilité", color: "bg-orange-400", itemId: "192357", quality: "non-bis-hm"},
	  arme1: {name: "Dague de finesse", color: "bg-yellow-300", itemId: "192358", quality: "bis-hm"},
	  arme2: {name: "Dague d'ombre", color: "bg-blue-300", itemId: "192359", quality: "bis-nm"},
	  ilvl: 666,
	  hasPermission: true
	},
	{
	  id: 20,
	  joueur: "Vol'jin",
	  classe: "Chaman",
	  specialisation: "Amélioration",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "202360", quality: "bis-nm"},
	  cou: {name: "Collier totémique", color: "bg-purple-500", itemId: "202345", quality: "non-bis-mm"},
	  epaules: {name: "Épaulières de fureur", color: "bg-yellow-300", itemId: "202346", quality: "bis-hm"},
	  cape: {name: "Cape des esprits", color: "bg-orange-400", itemId: "202347", quality: "non-bis-hm"},
	  torse: {name: "Harnois d'amélioration", color: "bg-purple-300", itemId: "202348", quality: "bis-mm"},
	  poignets: {name: "Brassards totémiques", color: "bg-blue-300", itemId: "202349", quality: "bis-nm"},
	  mains: {name: "Gants de fureur", color: "bg-yellow-300", itemId: "202350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture des esprits", color: "bg-purple-500", itemId: "202351", quality: "non-bis-mm"},
	  jambes: {name: "Kilt d'amélioration", color: "bg-blue-300", itemId: "202352", quality: "bis-nm"},
	  pieds: {name: "Bottes totémiques", color: "bg-orange-400", itemId: "202353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de fureur", color: "bg-purple-300", itemId: "202354", quality: "bis-mm"},
	  anneau2: {name: "Bague des esprits", color: "bg-blue-300", itemId: "202355", quality: "bis-nm"},
	  bijou1: {name: "Totem de fureur", color: "bg-yellow-300", itemId: "202356", quality: "bis-hm"},
	  bijou2: {name: "Charme d'amélioration", color: "bg-purple-500", itemId: "202357", quality: "non-bis-mm"},
	  arme1: {name: "Masse de fureur", color: "bg-blue-300", itemId: "202358", quality: "bis-nm"},
	  arme2: {name: "Hache des esprits", color: "bg-orange-400", itemId: "202359", quality: "non-bis-hm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 21,
	  joueur: "Darion",
	  classe: "Chevalier de la mort",
	  specialisation: "Sang",
	  role: "Tank",
	  tete: {name: "Heaume de sang", color: "bg-purple-300", itemId: "212360", quality: "bis-mm"},
	  cou: {name: "Collier vampirique", color: "bg-yellow-300", itemId: "212345", quality: "bis-hm"},
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "212346", quality: "bis-nm"},
	  cape: {name: "Cape de robustesse", color: "bg-orange-400", itemId: "212347", quality: "non-bis-hm"},
	  torse: {name: "Cuirasse de sang", color: "bg-purple-500", itemId: "212348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards vampiriques", color: "bg-blue-300", itemId: "212349", quality: "bis-nm"},
	  mains: {name: "Gantelets de robustesse", color: "bg-yellow-300", itemId: "212350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de sang", color: "bg-purple-300", itemId: "212351", quality: "bis-mm"},
	  jambes: {name: "Jambières vampiriques", color: "bg-blue-300", itemId: "212352", quality: "bis-nm"},
	  pieds: {name: "Bottes de robustesse", color: "bg-orange-400", itemId: "212353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de sang", color: "bg-purple-500", itemId: "212354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague vampirique", color: "bg-yellow-300", itemId: "212355", quality: "bis-hm"},
	  bijou1: {name: "Sceau de sang", color: "bg-blue-300", itemId: "212356", quality: "bis-nm"},
	  bijou2: {name: "Talisman de robustesse", color: "bg-purple-300", itemId: "212357", quality: "bis-mm"},
	  arme1: {name: "Lame runique de sang", color: "bg-yellow-300", itemId: "212358", quality: "bis-hm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 668,
	  hasPermission: true
	},
	{
	  id: 22,
	  joueur: "Chen",
	  classe: "Moine",
	  specialisation: "Marche-vent",
	  role: "DPS",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "222360", quality: "bis-nm"},
	  cou: {name: "Collier de célérité", color: "bg-orange-400", itemId: "222345", quality: "non-bis-hm"},
	  epaules: {name: "Épaulières de frappe", color: "bg-purple-300", itemId: "222346", quality: "bis-mm"},
	  cape: {name: "Cape de vent", color: "bg-yellow-300", itemId: "222347", quality: "bis-hm"},
	  torse: {name: "Tunique de marcheur", color: "bg-blue-300", itemId: "222348", quality: "bis-nm"},
	  poignets: {name: "Bandes de célérité", color: "bg-purple-500", itemId: "222349", quality: "non-bis-mm"},
	  mains: {name: "Gants de frappe", color: "bg-orange-400", itemId: "222350", quality: "non-bis-hm"},
	  ceinture: {name: "Ceinture de vent", color: "bg-blue-300", itemId: "222351", quality: "bis-nm"},
	  jambes: {name: "Pantalon de marcheur", color: "bg-yellow-300", itemId: "222352", quality: "bis-hm"},
	  pieds: {name: "Chaussons de célérité", color: "bg-purple-300", itemId: "222353", quality: "bis-mm"},
	  anneau1: {name: "Anneau de frappe", color: "bg-blue-300", itemId: "222354", quality: "bis-nm"},
	  anneau2: {name: "Bague de vent", color: "bg-purple-500", itemId: "222355", quality: "non-bis-mm"},
	  bijou1: {name: "Insigne de marcheur", color: "bg-yellow-300", itemId: "222356", quality: "bis-hm"},
	  bijou2: {name: "Talisman de célérité", color: "bg-orange-400", itemId: "222357", quality: "non-bis-hm"},
	  arme1: {name: "Arme de pugilat", color: "bg-purple-300", itemId: "222358", quality: "bis-mm"},
	  arme2: {name: "Arme de pugilat", color: "bg-blue-300", itemId: "222359", quality: "bis-nm"},
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 23,
	  joueur: "Tyrande",
	  classe: "Prêtre",
	  specialisation: "Sacré",
	  role: "Healer",
	  tete: {name: "Couronne sacrée", color: "bg-yellow-300", itemId: "232360", quality: "bis-hm"},
	  cou: {name: "Pendentif de lumière", color: "bg-blue-300", itemId: "232345", quality: "bis-nm"},
	  epaules: {name: "Set", color: "bg-purple-300", itemId: "232346", quality: "bis-mm"},
	  cape: {name: "Cape de guérison", color: "bg-orange-400", itemId: "232347", quality: "non-bis-hm"},
	  torse: {name: "Robe sacrée", color: "bg-purple-500", itemId: "232348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards de lumière", color: "bg-yellow-300", itemId: "232349", quality: "bis-hm"},
	  mains: {name: "Gants de guérison", color: "bg-blue-300", itemId: "232350", quality: "bis-nm"},
	  ceinture: {name: "Ceinture sacrée", color: "bg-purple-300", itemId: "232351", quality: "bis-mm"},
	  jambes: {name: "Jambières de lumière", color: "bg-orange-400", itemId: "232352", quality: "non-bis-hm"},
	  pieds: {name: "Sandales de guérison", color: "bg-yellow-300", itemId: "232353", quality: "bis-hm"},
	  anneau1: {name: "Anneau sacré", color: "bg-blue-300", itemId: "232354", quality: "bis-nm"},
	  anneau2: {name: "Bague de lumière", color: "bg-purple-500", itemId: "232355", quality: "non-bis-mm"},
	  bijou1: {name: "Symbole sacré", color: "bg-purple-300", itemId: "232356", quality: "bis-mm"},
	  bijou2: {name: "Charme de guérison", color: "bg-orange-400", itemId: "232357", quality: "non-bis-hm"},
	  arme1: {name: "Bâton sacré", color: "bg-yellow-300", itemId: "232358", quality: "bis-hm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 666,
	  hasPermission: true
	},
	{
	  id: 24,
	  joueur: "Malfurion",
	  classe: "Druide",
	  specialisation: "Gardien",
	  role: "Tank",
	  tete: {name: "Set", color: "bg-blue-300", itemId: "242360", quality: "bis-nm"},
	  cou: {name: "Amulette de la nature", color: "bg-purple-500", itemId: "242345", quality: "non-bis-mm"},
	  epaules: {name: "Épaulières d'écorce", color: "bg-yellow-300", itemId: "242346", quality: "bis-hm"},
	  cape: {name: "Cape de gardien", color: "bg-orange-400", itemId: "242347", quality: "non-bis-hm"},
	  torse: {name: "Harnois de la nature", color: "bg-purple-300", itemId: "242348", quality: "bis-mm"},
	  poignets: {name: "Brassards d'écorce", color: "bg-blue-300", itemId: "242349", quality: "bis-nm"},
	  mains: {name: "Gants de gardien", color: "bg-yellow-300", itemId: "242350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture de la nature", color: "bg-purple-500", itemId: "242351", quality: "non-bis-mm"},
	  jambes: {name: "Jambières d'écorce", color: "bg-blue-300", itemId: "242352", quality: "bis-nm"},
	  pieds: {name: "Bottes de gardien", color: "bg-orange-400", itemId: "242353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau de la nature", color: "bg-purple-300", itemId: "242354", quality: "bis-mm"},
	  anneau2: {name: "Bague d'écorce", color: "bg-blue-300", itemId: "242355", quality: "bis-nm"},
	  bijou1: {name: "Idole de gardien", color: "bg-yellow-300", itemId: "242356", quality: "bis-hm"},
	  bijou2: {name: "Charme de la nature", color: "bg-purple-500", itemId: "242357", quality: "non-bis-mm"},
	  arme1: {name: "Bâton de gardien", color: "bg-blue-300", itemId: "242358", quality: "bis-nm"},
	  arme2: {name: "", color: "", itemId: "", quality: ""}, // 2H weapon
	  ilvl: 667,
	  hasPermission: true
	},
	{
	  id: 25,
	  joueur: "Illidan",
	  classe: "Chasseur de démons",
	  specialisation: "Dévastation",
	  role: "DPS",
	  tete: {name: "Bandeau gangrené", color: "bg-purple-300", itemId: "252360", quality: "bis-mm"},
	  cou: {name: "Collier de haine", color: "bg-yellow-300", itemId: "252345", quality: "bis-hm"},
	  epaules: {name: "Set", color: "bg-blue-300", itemId: "252346", quality: "bis-nm"},
	  cape: {name: "Cape de dévastation", color: "bg-orange-400", itemId: "252347", quality: "non-bis-hm"},
	  torse: {name: "Harnois gangrené", color: "bg-purple-500", itemId: "252348", quality: "non-bis-mm"},
	  poignets: {name: "Brassards de haine", color: "bg-blue-300", itemId: "252349", quality: "bis-nm"},
	  mains: {name: "Gants de dévastation", color: "bg-yellow-300", itemId: "252350", quality: "bis-hm"},
	  ceinture: {name: "Ceinture gangrenée", color: "bg-purple-300", itemId: "252351", quality: "bis-mm"},
	  jambes: {name: "Jambières de haine", color: "bg-blue-300", itemId: "252352", quality: "bis-nm"},
	  pieds: {name: "Bottes de dévastation", color: "bg-orange-400", itemId: "252353", quality: "non-bis-hm"},
	  anneau1: {name: "Anneau gangrené", color: "bg-purple-500", itemId: "252354", quality: "non-bis-mm"},
	  anneau2: {name: "Bague de haine", color: "bg-yellow-300", itemId: "252355", quality: "bis-hm"},
	  bijou1: {name: "Insigne de dévastation", color: "bg-blue-300", itemId: "252356", quality: "bis-nm"},
	  bijou2: {name: "Talisman gangrené", color: "bg-purple-300", itemId: "252357", quality: "bis-mm"},
	  arme1: {name: "Glaive de guerre", color: "bg-yellow-300", itemId: "252358", quality: "bis-hm"},
	  arme2: {name: "Glaive de guerre", color: "bg-blue-300", itemId: "252359", quality: "bis-nm"},
	  ilvl: 670,
	  hasPermission: true
	}
];